name=jsonbuildersink
debezium.source.connector.class=io.debezium.connector.mysql.MySqlConnector
debezium.source.offset.storage=org.apache.kafka.connect.storage.FileOffsetBackingStore
debezium.source.offset.storage.file.filename=/tmp/offsets_connector-stock.dat
debezium.source.offset.flush.interval.ms=60000
debezium.source.database.hostname=127.0.0.1
debezium.source.database.port=3306
debezium.source.database.user=debezium
debezium.source.database.password=dbz
debezium.source.database.include.list=tpcc
debezium.source.database.server.id=184054
debezium.source.topic.prefix=cdc
debezium.source.schema.history.internal=io.debezium.storage.file.history.FileSchemaHistory
debezium.source.schema.history.internal.file.filename=/tmp/schemahistory_connector-stock.dat
debezium.source.snapshot.mode=no_data
debezium.source.heartbeat.interval.ms=10000
debezium.source.max.batch.size=100000
debezium.source.max.queue.size=300000
debezium.source.poll.interval.ms=10000
debezium.sink.type=jsonbuilder
debezium.format.value=json
quarkus.log.file.enable=true
quarkus.log.file.path=logs/debezium.log
quarkus.log.file.rotation.max-file-size=20M
quarkus.log.file.rotation.max-backup-index=5
quarkus.log.category."io.debezium.server.console".level=TRACE
quarkus.log.console.level=TRACE
quarkus.log.file.level=TRACE
quarkus.log.min-level=TRACE
quarkus.log.console.json.pretty-print=true


quarkus.log.handler.file.my-class-file-handler.enable=true
quarkus.log.handler.file.my-class-file-handler.path=/path/to/your/logs/my-class-logs.log
quarkus.log.handler.file.my-class-file-handler.level=INFO
quarkus.log.handler.file.my-class-file-handler.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n
# Optional: configure rotation if needed
# quarkus.log.handler.file.my-class-file-handler.rotation.max-file-size=10M
# quarkus.log.handler.file.my-class-file-handler.rotation.file-suffix=.yyyy-MM-dd

# Custom JSON Builder log handler
quarkus.log.handler.jsonbuilder.type=file
quarkus.log.handler.jsonbuilder.path=logs/jsonbuilder.log
quarkus.log.handler.jsonbuilder.level=TRACE
quarkus.log.handler.jsonbuilder.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n
quarkus.log.handler.jsonbuilder.rotation.max-file-size=50M
quarkus.log.handler.jsonbuilder.rotation.max-backup-index=50

# Attach to class logger
quarkus.log.category."io.debezium.server.jsonbuilder.JsonBuilderChangeConsumer".level=TRACE
quarkus.log.category."io.debezium.server.jsonbuilder.JsonBuilderChangeConsumer".handlers=jsonbuilder
quarkus.log.category."io.debezium.server.jsonbuilder.JsonBuilderChangeConsumer".use-parent-handlers=false



