{
 "title": "WIP",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Bytes In",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(topic) (kafka_server_brokertopicmetrics_bytesin_total{job=\"kafka\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes out",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(topic) (kafka_server_brokertopicmetrics_bytesout_total{job=\"kafka\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Message in",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(topic) (kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fetch Requests",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(topic) (kafka_server_brokertopicmetrics_totalfetchrequests_total{job=\"kafka\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log size",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(topic) (kafka_log_log_size{job=\"kafka\"}) /1024 / 1024 /1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}